### ISSUE TITLE
[Errno 17] File exists:'/krita_blender_layer:56432'

### ISSUE THREAD

**Issue by jurassicjordan** [Yuntokon/BlenderLayer#1]
I closed blender accidentally and it caused krita to (what I assume) crash, leaving this mysterious file behind. Please help

**Comment by Yuntokon** [comment]
For people who have the same issue: The file is just the shared memory buffer, so after a while it should be cleaned up automatically. In the meantime you can still change the port number in settings to use a different file or temporarily disable shared memory in settings
