### ISSUE TITLE
[Errno 32] Broken Pipe Error while trying to connect manually to blender Linux.

### ISSUE THREAD

**Issue by AmyRoxwell** [Yuntokon/BlenderLayer#2]
When trying to connect blender and krita with the start server option on krita, "[Errno 32] Broken Pipe" will show up on krita and blender will fail to connect, if you instead do "start blender" it will work perfectly and you can even disconnect and reconnect without issue.|
Blender Version: Steam Blender 3.5, Linux ver
Krita Version: Official Flatpak 5.1.5
Sadly the terminal doesn't spit any error messages, so the only thing i can show is the error image
![image](https://github.com/Yuntokon/BlenderLayer/assets/89411895/ce6c2538-2f87-42f0-9b48-e738f67ed782)

**Comment by phelipefox** [comment]
Hello! You need to give the Flatpak Krita app permission to see the blender executable directory.

You can do this by running this command in the terminal:
`flatpak override --user --filesystem=/home/YOUR_USER_NAME/.local/share/flatpak/app/org.blender.Blender org.kde.krita `

**Comment by Yuntokon** [comment]
It might also be worth to try disabling shared mem by going to the settings in the docker (button at the bottom right of the blender layer docker, under connection untick ‘use shared memory buffer’).

**Comment by Yuntokon** [comment]
Closed. Open a new issue if you experience the same problem and the above suggestions do not work.

**Comment by Yuntokon** [comment]
Closed. Open a new issue if you experience the same problem and the above suggestions do not work.
