### ISSUE TITLE
addon not visible to activation

### ISSUE THREAD

**Issue by jolhirsute** [Yuntokon/BlenderLayer#4]
Hello
thank you for your effort but it seems that Krita not see your addon.
I put the folder and the .desktop file in the right place and it is not visible after restart.
The version of Krita is 5.2.0

**Comment by Yuntokon** [comment]
Should work on 5.2.0. Does it not show up at all? Even when there is an error it should be just greyed out in the Plugin Manager, not completely absent. Double check the install location (see)[https://docs.krita.org/en/user_manual/python_scripting/install_custom_python_plugin.html#install-custom-python-plugins]
You could also try using the "Install Python Plugin from File..." action. Have you had this issue with any other plugin?

**Comment by jolhirsute** [comment]
Hello and thanks for your message.
My version is the 2.5.1 in windows 10
terribly sorry but it isn't visible. The instal go well and propose to activate the plugin. But when I restart : nothing.
I have test the import plugin and manual installation.
In pykrita folder I have a stable_diffusion_krita plugin and is not visible too.





jolhirsute
 
From: Yuntoko
Date: 10-11-2023 16:41
To: Yuntokon/BlenderLayer
CC: jolhirsute; Author
Subject: Re: [Yuntokon/BlenderLayer] addon not visible to activation (Issue #4)
Should work on 5.2.0. Does it not show up at all? Even when there is an error it should be just greyed out in the Plugin Manager, not completely absent. Double check the install location (see)[https://docs.krita.org/en/user_manual/python_scripting/install_custom_python_plugin.html#install-custom-python-plugins]
You could also try using the "Install Python Plugin from File..." action. Have you had this issue with any other plugin?

**Comment by Yuntokon** [comment]
Closed, as this does not appear to be specific to this addon.
