### ISSUE TITLE
Add depth map to plugin.

### ISSUE THREAD

**Issue by VRVirtuosos** [Yuntokon/BlenderLayer#6]
If we had the ability to generate a depth map from the model we could then use Stable Diffusion Ai krita plugin to generate textures to use directly on the models.  This is a feature request and not a bug report,

**Comment by Yuntokon** [comment]
Sorry for the late reply. This can be achieved without any changes to the plugin: Simply set viewport shading to 'Render Preview' and set Render pass to 'Mist'. The Mist Pass can be configured in Word Properties. If you need the inverse i.e. lighter is closer, just add an invert filter layer in Krita.

That being said, I am somewhat skeptical this is the best approach to get depth maps into Stable Diffusion. I'm pretty sure there are addons for combining Stable Diffusion directly with Blender, there is no need to use Krita and two additional plugins as intermediaries.
