### ISSUE TITLE
Krita freezes

### ISSUE THREAD

**Issue by cheshirecatt** [Yuntokon/BlenderLayer#8]
In the latest version of Krita, the plugin causes Krita to freeze after opening Blender.

**Comment by Yuntokon** [comment]
Should be fixed now, try reinstalling the plugin in Krita.

**Comment by cheshirecatt** [comment]
Works perfect now, thank you so much!

![imagen](https://github.com/user-attachments/assets/5d231f32-e716-45f0-9215-dcabbb0c7cf1)
